Damaged Sable Guppy

High

# Won prizes may get permanently locked due to out-of-gas reverts

### Summary

Implementation of [WinnablesTicket::ownerOf](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicket.sol#L93-L101) is prone to out-of-gas reverts, thus causing permanent locking of the prize, which the rightful winner won't be able to receive.

### Root Cause


[WinnablesTicket::ownerOf](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicket.sol#L93-L101) performs a backward iteration over ticket numbers starting from the winning ticket number and till the starting number of the batch of bought tickets:

```solidity
while (_ticketOwnership[id][ticketId] == address(0)) {
  unchecked { --ticketId; }
}
```

The function above is called in `WinnablesTicketManager` from [propagateRaffleWinner](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L334-L345) via [_getWinnerByRequestId](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L472-L477); thus the revert in `WinnablesTicket::ownerOf` will cause the raffle winner not propagated, and the winner won't be able to claim the prize.

### Internal pre-conditions

1. A user buys a large enough ticket batch (>= `12608`);
2. A randomly drawn winning ticket is >= `12607` from the ticket batch start. 

These numbers seem entirely realistic because:

- The maximum number of tickets bought is `type(uint16).max = 65535`
- There are already running / finished raffles with the numbers very close to those needed to trigger the bug, e.g. the [Long Running Raffle](https://testnet.winnables.com/competitions/18) has max tickets `60000`, out of which at the time of writing `7043` are sold, and the largest sold batch contains `4347` tickets.


### External pre-conditions

none

### Attack Path

No attack is necessary. The bug will trigger by itself, when internal preconditions are met.

### Impact

Permanent locking of a prize, which the rightful winner won't be able to claim. Morever, an admin of `WinnablesPrizeManager` won't be able to recover (withdraw) the prize either, as it is locked.

### PoC

Apply the following diff, and run with `yarn test`:

```diff
diff --git a/public-contracts/test/Ticket.js b/public-contracts/test/Ticket.js
index d7c2683..05dae09 100644
--- a/public-contracts/test/Ticket.js
+++ b/public-contracts/test/Ticket.js
@@ -74,9 +74,12 @@ describe('CCIP Ticket Manager', () => {
       );
     });
 
+    const numTickets = 13000;
+    const failTicket = 12607;
+
     it('Mints tickets to regular address', async () => {
       await (await ticket.setRole(signers[0].address, 1, true)).wait();
-      const { events } = await (await ticket.mint(signers[1].address, 1, 1)).wait();
+      const { events } = await (await ticket.mint(signers[1].address, 1, numTickets)).wait();
       expect(events).to.have.lengthOf(2);
       expect(events[0].event).to.eq('NewTicket');
       expect(events[1].event).to.eq('TransferSingle');
@@ -117,24 +120,24 @@ describe('CCIP Ticket Manager', () => {
     });
 
     it('Supports ownership query for ticket numbers', async () => {
-      const ticketOwner = await ticket.ownerOf(1, 0);
+      const ticketOwner = await ticket.ownerOf(1, failTicket);
       expect(ticketOwner).to.eq(signers[1].address);
     });
 
     it('Supports checks for ticket number existence', async () => {
-      await expect(ticket.ownerOf(1, 1)).to.be.revertedWithCustomError(ticket, 'InexistentTicket');
+      await expect(ticket.ownerOf(1, numTickets)).to.be.revertedWithCustomError(ticket, 'InexistentTicket');
     })
 
     it('Supports balance queries', async () => {
       expect(await ticket.balanceOf(signers[0].address, 1)).to.eq(0);
-      expect(await ticket.balanceOf(signers[1].address, 1)).to.eq(1);
+      expect(await ticket.balanceOf(signers[1].address, 1)).to.eq(numTickets);
       await expect(ticket.balanceOfBatch([signers[1].address], [1, 2])).to.be.revertedWithCustomError(
         ticket,
         'InconsistentParametersLengths'
       );
       const balances = await ticket.balanceOfBatch([signers[1].address], [1]);
       expect(balances).to.have.lengthOf(1);
-      expect(balances[0]).to.eq(1);
+      expect(balances[0]).to.eq(numTickets);
     });
   });
 
```

In the above we had to generalize a couple of tests via introduction of auxiliary constants `numTickets` (number of tickets in a batch), and `failTicket` (the randomly drawn ticket, sufficiently far from the batch start). The above test fails with

```sh
 1 failing

  1) CCIP Ticket Manager
       Ticket behaviour
         Supports ownership query for ticket numbers:
     Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266","gasLimit":{"type":"BigNumber","hex":"0x01bad618"},"to":"0x67d269191c92Caf3cD7723F116c85e6E9bf55933","data":"0xd9dad80d0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000313f","accessList":null}, error={"name":"ProviderError","_stack":"ProviderError: Transaction ran out of gas\n    at EdrProviderWrapper.request
```


### Mitigation

Don't iterate over all ticket numbers; instead, store starting numbers of bought ticket batches in an array, and iterate over this array.